name: Hi Workflow
on: push
jobs: 
  any-name-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to find repo
      uses: actions/checkout@v4
    - name: Welcome
      run: |
        echo "Hi repo"
        ls -a
    - name: Read readme
      run: cat README.md
  another-job:
    needs: any-name-job
    runs-on: ubuntu-latest
    steps:
    - name: Tell smth
      uses: actions/checkout@v4
    - name: Say smth
      run: echo "Second job"
