name: hi (old)
on: push
jobs: 
  any-name-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to find repo
      uses: actions/checkout@v4
    - name: Welcome
      run: |
        echo "Hi repo"
        ls
